# Vanilla CNN

Code for Vanilla CNN based baseline model

## Imports

In [1]:
import numpy as np
import pandas as pd
import os, random
import cv2
import matplotlib.pyplot as plt
from tqdm import tqdm

In [2]:
!pip install openpyxl

!pip install wandb
!wandb login
import wandb

wandb.init(project="228-project", entity="szddhant")
!nvidia-smi

Defaulting to user installation because normal site-packages is not writeable
/bin/bash: wandb: command not found


Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: szddhant. Use `wandb login --relogin` to force relogin


Wed Jun  1 13:00:55 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 460.67                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:61:00.0 Off |                  N/A |
|  0%   41C    P8     1W / 260W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

## Dataloader

In [3]:
path = "/home/ssaoji/228_Project/Aug_Seg/Augmented_Segmented_data/"#Final_Augmented_Data/" # path to augmented data
folders = ['Scale']#['Flip','Rotate','Scale','Translation']
for f in folders:
  print(len(os.listdir(path+f)))

211


In [4]:
class DataLoader():
  def __init__(self) -> None:
      self.path = "/home/ssaoji/228_Project/Aug_Seg/Augmented_Segmented_data/" # path to augmented data#"/content/drive/MyDrive/Course_files/228/dataset_anemia/Final_Augmented_Data/" # path to augmented data
      self.folders = ['Flip','Rotate','Scale','Translation']
      self.y_india = pd.read_excel(r'/home/ssaoji/228_Project/dataset_anemia/India/India.xlsx')#np.load("/content/drive/MyDrive/Course_files/228/dataset_anemia/y_india.npy")
      self.y_italy = pd.read_excel(r'/home/ssaoji/228_Project/dataset_anemia/Italy/Italy_copy.xlsx')#np.load("/content/drive/MyDrive/Course_files/228/dataset_anemia/y_base_italy.npy")
      # self.split = 1#0.5 #italy/india split
      self.skip = 95 #Skip value in Italy (No value)
      self.split = [0.8,0.1,0.1] #train,val,test
  def sample(self,num,j):
    # num_italy = int(num*self.split)
    # num_india = num - num_italy
    X = np.zeros((num,640,480,3))
    Y = np.zeros(num)
    seen =[]
    for i in range(num):
      f = np.random.randint(0,len(folders))
      path = self.path+self.folders[f]
      l = os.listdir(path)
      if j ==0:
        im_p = os.listdir(path)[0:int(len(l)*self.split[j])]
      else:
        im_p = os.listdir(path)[int(len(l)*self.split[j-1]):int(len(l)*self.split[j])]
      image = random.choice(os.listdir(path))
      name_list = image.replace(".jpg","").split('_')
      country = name_list[0]
      id = int(name_list[1])
      if country =='italy':
        try:
          s = d.y_italy["Number"]==id
          s[s==True].index[-1]
          Y[i] = float(self.y_italy['Hgb'][s])/20
        except:
          continue
      elif country =='india':
        s = d.y_india["Number"]==float(id)
        s[s==True].index[-1]
        Y[i] = float(self.y_india['Hgb'][s])/20
#         temp =cv2.imread(path+'/' + image)
#         X[i,:,:,:] = cv2.cvtColor(temp, cv2.COLOR_BGR2HSV)/255
        img = cv2.imread(path+'/' + image)
#         img_yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
#         # equalize the histogram of the Y channel
#         img_yuv[:,:,0] = cv2.equalizeHist(img_yuv[:,:,0])
#         # convert the YUV image back to RGB format
#         img_output = cv2.cvtColor(img_yuv, cv2.COLOR_YUV2BGR)
        X[i,:,:,:] =  img/255
    X = np.array(X)
    Y = np.array(Y)
    return X,Y
  def sample_v(self,num,j):
    # num_italy = int(num*self.split)
    # num_india = num - num_italy
    X = np.zeros((num,640,480,3))
    Y = np.zeros(num)
    seen =[]
    for i in range(num):
      # f = np.random.randint(0,?len(folders))
      path = self.path+"Scale"
      l = os.listdir(path)
      im_p = os.listdir(path)[int(len(l)*self.split[j-1]):int(len(l)*self.split[j])]
      image = random.choice(os.listdir(path))
      name_list = image.replace(".jpg","").split('_')
      country = name_list[0]
      id = int(name_list[1])
      if country =='italy':
        try:
          s = d.y_italy["Number"]==id
          s[s==True].index[-1]
          Y[i] = float(self.y_italy['Hgb'][s])/20
        except:
          continue
      elif country =='india':
        s = d.y_india["Number"]==float(id)
        s[s==True].index[-1]
        Y[i] = float(self.y_india['Hgb'][s])/20
        temp =cv2.imread(path+'/' + image)
# #         print(temp.shape)
#         img_yuv = cv2.cvtColor(temp, cv2.COLOR_BGR2YUV)

#         # equalize the histogram of the Y channel
#         img_yuv[:,:,0] = cv2.equalizeHist(img_yuv[:,:,0])
    
#         # convert the YUV image back to RGB format
#         temp = cv2.cvtColor(img_yuv, cv2.COLOR_YUV2BGR)
        X[i,:,:,:] =  temp/255#cv2.cvtColor(temp, cv2.COLOR_BGR2HSV)/255

#       cv::COLOR_BGR2Lab(temp)
    X = np.array(X)
    Y = np.array(Y)
    return X,Y

In [5]:
# s = d.y_italy["Number"]==91
# s[s==True].index[-1]
d = DataLoader()
# d.test()?

Defaulting to user installation because normal site-packages is not writeable


In [6]:
# d = DataLoader()
# z = 100
# x,Y = d.sample(z,0)
# X =np.zeros((z,3,640,480))
# X[:,0,:,:] = x[:,:,:,0]
# X[:,2,:,:] = x[:,:,:,1]
# X[:,2,:,:] = x[:,:,:,2]
# # # X.shape
# # x.shape
# # plt.imshow(x[0])

In [7]:
import torch
import torchvision
import torchvision.transforms as transforms

In [8]:
# train_split=0.9
# val_split = 0.05
# test_split = 1 - train_split - val_split
# batch_size = 3
# epochs = 10

# X=X[:,:,:]
# X_in = torch.tensor(X).float()
# X_in.size()

# y_in = torch.tensor(Y).float().unsqueeze(1)

# print(X_in.shape, y_in.shape)

## CNN model

In [9]:
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 16, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(16, 16, 5)
        self.fc1 = nn.Linear(293904, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 1)
        self.relu = nn.LeakyReLU()
        self.sigmoid = nn.Sigmoid()
        self.dropout = nn.Dropout(0.25)


    def forward(self, x):
        x = self.pool(self.relu(self.conv1(x)))
        x = self.pool(self.relu(self.conv2(x)))
        x = torch.flatten(x, 1) # flatten all dimensions except batch
        x = self.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.relu(self.fc2(x))
        x = self.dropout(x)
        x = self.sigmoid(self.fc3(x))
        # x = self.fc3(x)
        return x

net = Net()
net = net.cuda()

## Model Training

In [10]:
import torch.optim as optim
# check GPU availability
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cuda:0


In [11]:
criterion = nn.MSELoss()
criterion = criterion.cuda()
# optimizer = optim.SGD(net.parameters(), lr=0.01, momentum=0.9)
optimizer = optim.Adam(net.parameters(), lr=0.001)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=2, gamma=0.9)

In [12]:
batch_size = 100
epochs = 20
batches = 10
wandb.config = {
  "learning_rate": 0.001,
  "epochs": epochs,
  "batch_size": batch_size,
  "batches" : batches
}


d = DataLoader()
x,Y = d.sample_v(10,1)
X =np.zeros((10,3,640,480))
X[:,0,:,:] = x[:,:,:,0]
X[:,1,:,:] = x[:,:,:,1]
X[:,2,:,:] = x[:,:,:,2]
y_val = torch.tensor(Y).float().unsqueeze(1).to(device)
X_val = torch.tensor(X).float().to(device)

for epoch in tqdm(range(epochs)):  # loop over the dataset multiple times
    running_loss = 0.0
    validation_loss = 0.0
    # iters = (len(X_train)//batch_size)+1
    for i in range(batches):
      x,Y = d.sample(batch_size,0)
      X =np.zeros((batch_size,3,640,480))
      X[:,0,:,:] = x[:,:,:,0]
      X[:,1,:,:] = x[:,:,:,1]
      X[:,2,:,:] = x[:,:,:,2]
      X=X[:,:,:]
      inputs = torch.tensor(X).float().to(device)
      labels = torch.tensor(Y).float().unsqueeze(1).to(device)
      optimizer.zero_grad()

      # forward + backward + optimize
      outputs = net(inputs)
      loss = criterion(outputs, labels)
      loss.backward()
      optimizer.step()
      
      # print statistics
      running_loss += loss.item()
        
    with torch.no_grad():
      y_pred_val = net(X_val)
      print(y_pred_val)
      val_loss = criterion(y_pred_val, y_val)
#       val_loss20 = criterion(y_pred_val*20, y_val*20)
      validation_loss += val_loss.item()    
      wandb.log({"loss": running_loss/batches,"loss_scaled": 400*(running_loss/batches),"val_loss":val_loss,"val_loss_scaled":val_loss*400})
      wandb.watch(net)


#       print(f'[{epoch + 1}] loss: {running_loss :.9f}, val_loss: {val_loss.item():.3f}, val_loss20: {val_loss20.item():.3f}')
        # running_loss = 0.0
        # validation_loss = 0.0
      scheduler.step()

  0%|          | 0/20 [00:00<?, ?it/s]/opt/conda/lib/python3.9/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
  5%|▌         | 1/20 [00:25<08:09, 25.75s/it]

tensor([[0.6593],
        [0.6920],
        [0.6878],
        [0.7038],
        [0.6656],
        [0.6480],
        [0.6370],
        [0.5932],
        [0.6376],
        [0.6103]], device='cuda:0')


 10%|█         | 2/20 [00:54<08:12, 27.36s/it]

tensor([[0.6518],
        [0.6232],
        [0.6347],
        [0.5839],
        [0.7510],
        [0.5148],
        [0.5727],
        [0.6868],
        [0.5810],
        [0.6684]], device='cuda:0')


 15%|█▌        | 3/20 [01:21<07:44, 27.33s/it]

tensor([[0.6885],
        [0.6532],
        [0.7409],
        [0.6462],
        [0.7139],
        [0.6090],
        [0.5523],
        [0.7585],
        [0.6067],
        [0.7017]], device='cuda:0')


 20%|██        | 4/20 [01:49<07:20, 27.54s/it]

tensor([[0.7463],
        [0.6172],
        [0.6234],
        [0.6895],
        [0.7120],
        [0.6520],
        [0.5796],
        [0.7101],
        [0.6259],
        [0.6360]], device='cuda:0')


 25%|██▌       | 5/20 [02:16<06:49, 27.28s/it]

tensor([[0.5958],
        [0.6562],
        [0.6357],
        [0.5849],
        [0.6219],
        [0.6543],
        [0.5544],
        [0.6446],
        [0.5690],
        [0.6387]], device='cuda:0')


 30%|███       | 6/20 [02:43<06:22, 27.31s/it]

tensor([[0.6600],
        [0.6460],
        [0.7014],
        [0.6450],
        [0.6658],
        [0.5946],
        [0.5511],
        [0.6615],
        [0.6116],
        [0.6370]], device='cuda:0')


 35%|███▌      | 7/20 [03:10<05:54, 27.27s/it]

tensor([[0.6240],
        [0.6646],
        [0.7046],
        [0.6344],
        [0.6218],
        [0.6781],
        [0.5966],
        [0.6809],
        [0.6219],
        [0.7018]], device='cuda:0')


 40%|████      | 8/20 [03:36<05:23, 26.93s/it]

tensor([[0.6457],
        [0.6769],
        [0.6239],
        [0.6003],
        [0.7015],
        [0.6316],
        [0.5968],
        [0.7433],
        [0.6038],
        [0.7640]], device='cuda:0')


 45%|████▌     | 9/20 [04:04<04:59, 27.24s/it]

tensor([[0.7024],
        [0.6160],
        [0.6694],
        [0.6648],
        [0.7128],
        [0.6186],
        [0.5127],
        [0.6938],
        [0.5824],
        [0.6749]], device='cuda:0')


 50%|█████     | 10/20 [04:30<04:26, 26.65s/it]

tensor([[0.6801],
        [0.6733],
        [0.6955],
        [0.6592],
        [0.6796],
        [0.6836],
        [0.6109],
        [0.7182],
        [0.6398],
        [0.7094]], device='cuda:0')


 55%|█████▌    | 11/20 [04:56<03:58, 26.55s/it]

tensor([[0.6527],
        [0.6190],
        [0.6522],
        [0.6337],
        [0.7181],
        [0.6025],
        [0.5495],
        [0.7273],
        [0.5764],
        [0.6539]], device='cuda:0')


 60%|██████    | 12/20 [05:22<03:30, 26.28s/it]

tensor([[0.7452],
        [0.6296],
        [0.6823],
        [0.6395],
        [0.7205],
        [0.6809],
        [0.6254],
        [0.7041],
        [0.6370],
        [0.6880]], device='cuda:0')


 65%|██████▌   | 13/20 [05:47<03:01, 25.96s/it]

tensor([[0.6582],
        [0.6511],
        [0.6640],
        [0.6152],
        [0.7480],
        [0.6917],
        [0.6093],
        [0.6200],
        [0.6502],
        [0.6959]], device='cuda:0')


 70%|███████   | 14/20 [06:14<02:37, 26.23s/it]

tensor([[0.6596],
        [0.6502],
        [0.6655],
        [0.6578],
        [0.6664],
        [0.6710],
        [0.6281],
        [0.6422],
        [0.7113],
        [0.6486]], device='cuda:0')


 75%|███████▌  | 15/20 [06:40<02:11, 26.26s/it]

tensor([[0.6761],
        [0.6191],
        [0.6944],
        [0.6579],
        [0.6707],
        [0.6499],
        [0.5837],
        [0.6434],
        [0.6515],
        [0.6760]], device='cuda:0')


 80%|████████  | 16/20 [07:07<01:46, 26.57s/it]

tensor([[0.7163],
        [0.5704],
        [0.6503],
        [0.6858],
        [0.6522],
        [0.6895],
        [0.6328],
        [0.6473],
        [0.7014],
        [0.7218]], device='cuda:0')


 85%|████████▌ | 17/20 [07:33<01:18, 26.22s/it]

tensor([[0.7026],
        [0.6139],
        [0.6867],
        [0.7017],
        [0.6520],
        [0.7236],
        [0.6670],
        [0.6789],
        [0.6417],
        [0.6571]], device='cuda:0')


 90%|█████████ | 18/20 [07:59<00:52, 26.25s/it]

tensor([[0.6803],
        [0.6668],
        [0.6951],
        [0.6662],
        [0.6647],
        [0.6969],
        [0.6436],
        [0.6754],
        [0.7038],
        [0.7068]], device='cuda:0')


 95%|█████████▌| 19/20 [08:24<00:25, 25.85s/it]

tensor([[0.6901],
        [0.6413],
        [0.7152],
        [0.6460],
        [0.6446],
        [0.7547],
        [0.6026],
        [0.6850],
        [0.6779],
        [0.7041]], device='cuda:0')


100%|██████████| 20/20 [08:49<00:00, 26.46s/it]

tensor([[0.6981],
        [0.6847],
        [0.6694],
        [0.6773],
        [0.6514],
        [0.6896],
        [0.6144],
        [0.7036],
        [0.6915],
        [0.6612]], device='cuda:0')


In [18]:
with torch.no_grad():
    print(net(X_val)*20)
print(y_val*20)

tensor([[13.3513],
        [12.7423],
        [13.1603],
        [12.3455],
        [13.6965],
        [14.4038],
        [12.2098],
        [14.2865],
        [13.4996],
        [13.4088]], device='cuda:0')
tensor([[15.4000],
        [13.0000],
        [15.5000],
        [12.9000],
        [13.5000],
        [12.2000],
        [ 9.2000],
        [14.7000],
        [15.5000],
        [15.1000]], device='cuda:0')
