# Hue Score + SVM

Implementation of the HSI based SVM model based this [paper](https://pdf.sciencedirectassets.com/271322/1-s2.0-S0169260716X00144/1-s2.0-S0169260716302474/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEND%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJGMEQCICOZXQ2JjOwjOw2DtXtt1%2BAPu8NdWCKQA3IVQkHBIkHPAiB6IaAMrwKcE5yh8LkFdXyV2mI7d9udtLL4MLCvBe%2FDnSrbBAiY%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAQaDDA1OTAwMzU0Njg2NSIMhQtnypz22jLFKTaGKq8ESR6fKQsg1yBV6DSUUXW6GAk6RxUNk14Pd1qwwI8UwJfYCpbneVKCDftEWGH9ngvUNCTopF%2FJMWK4%2BVft4GwgWSdHlsY0KTF6UzWgWvK7gp%2FRJJvaNVpcZKklIUtqqz88G72Uvp0NnGpztyoRbr952e2XXNHIyyvgrILsUnE2BvBbbtmbCLOd%2FWGi1n6AKrvgK0OzxYClUFQFsXZqr%2BzfxWzLeeOsNYBqWJ2erGkW4FSJ0a5CtIS1MHoR1nIb1XK3Xzsk0rFA9O72wYl7ksgMUPCmKLA3WgxgA5D0bsgiTKi0FTxBr8nc9FQ4SOPf6rqNCc0F4f7DJCto4thOHn86bqQ6baKEyXfpik3Ew1M0TC5UiVcQ8AhT39jsbCFFwUkl1RZGEhBjsJqA91GA87XKeub2BqtRB5zt6dIpP99sBUKttW%2BNHGRX3yBD9wYc4CrAZmBEWYidsf5zv7vkP0pb1rp7vfofWi5GWeYP9bPUUnyvXJ3vBi0FOM36WLGJhSZnGcYJYghW3L6UYXa5pGMrejF09RhkN5rUH%2FxFOFeiAmKSQLmCRcMd4jDxC4Gxz%2BxabhYJYtHeyYtlORjuvcwasTX9ZWRjschkPD4MUvl0R3svm6FbbK%2Bp6qYNs5q7KJz%2BiOyYQwRurWHGl7YmGy5DexfDVYjGi%2Fug6dv%2BLs3m%2Bax2DXpceN3EopKrFQJqwheZztNdaqxJu9yaqS1APLO%2F47s7Nkllp6JDchP3sBmNkTDrt9GTBjqqATKOR9kgAuJJ9FLghsZYlmXGZ8XZnItsn%2BJMMySCAFN2RHcUeoIEZTY%2B8KZ8Zlfdfh1TrrsNpUQ0N%2BgmxFlKV%2FNC4HnGarRXgsKUsOlz1zbgJCHP%2BMqod9UNGyGjCEG335q%2FOemAEoSv%2BaDkDpeqk9ggrSdAEETXZbsuLQXnnAotdvxGFBQowEZpBJfgjy1I2Mrqbu%2BF8TuzT5WFZswAaxzKjMQF%2FByK%2FWRD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220506T002956Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTYVF7RPVNQ%2F20220506%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=c7e5d0d717ff7abc0b84467c6c740679d45fbb3689cd091474a210dc27db1b51&hash=049113929a06b6b3c4daa70d86672380060d89a2614a0527024677c18e71c6e8&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S0169260716302474&tid=spdf-fa3b6875-a31a-405c-a6fb-6f7481dcf922&sid=405aae1354c8544fc74b463615e16257ffa7gxrqa&type=client&ua=595353045d070d0402&rr=706d9abbda757e77) 

## Reference
Chen, Yi-Ming, Shaou-Gang Miaou, and Hongyu Bian. "Examining palpebral conjunctiva for anemia assessment with image processing methods." Computer methods and programs in biomedicine 137 (2016): 125-135.

## Imports

In [1]:
from matplotlib import pyplot as plt
import cv2
import numpy as np
import pandas
from tqdm import tqdm

In [2]:
import torch
import torchvision
import torchvision.transforms as transforms

## Load Data

In [3]:
y_it = np.load(r"C:\Users\manas\Documents\Winter 2022\Digital Health Systems\Project\anemia_detection\y_forniceal_italy.npy") #/30
X_it = np.load(r"C:\Users\manas\Documents\Winter 2022\Digital Health Systems\Project\anemia_detection\X_forniceal_italy.npy")/255

In [4]:
y_in = np.load(r"C:\Users\manas\Documents\Winter 2022\Digital Health Systems\Project\anemia_detection\y_forniceal_india.npy") #/30
X_in = np.load(r"C:\Users\manas\Documents\Winter 2022\Digital Health Systems\Project\anemia_detection\X_forniceal_india.npy")/255

In [41]:
X_it = np.load(r"C:\Users\manas\Documents\Winter 2022\Digital Health Systems\Project\anemia_detection\X_proc_italy.npy")/255
X_in = np.load(r"C:\Users\manas\Documents\Winter 2022\Digital Health Systems\Project\anemia_detection\X_proc_india.npy")/255

y_it = np.load(r"C:\Users\manas\Documents\Winter 2022\Digital Health Systems\Project\anemia_detection\y_base_italy.npy")
y_in = np.load(r"C:\Users\manas\Documents\Winter 2022\Digital Health Systems\Project\anemia_detection\y_base_india.npy")

In [51]:
X_npy = np.concatenate((X_in, X_it), axis=0).astype(np.float32)
y_npy = np.concatenate((y_in, y_it), axis=0)/20
X_npy.shape, y_npy.shape

((218, 640, 480, 1), (218,))

## Data Preparation and feature computation

In [66]:
X_npy2 = np.stack((X_npy, X_npy, X_npy), axis=3)[:,:,:,:,0]

In [67]:
X_new = []
for i in range(len(X_npy)):
    X_new.append(cv2.cvtColor(X_npy2[i], cv2.COLOR_BGR2HLS))
X_new = np.array(X_new)

In [68]:
X_h = X_new[:,:,:,0].copy()
X_h_backup = X_h.copy()
X_h.max(), X_h.min()

(0.0, 0.0)

In [69]:
T = 100 # from paper
X_h[X_h >= T] = 1
X_h[X_h < 1] = 0

In [70]:
X_hhr = X_h.sum(axis=(1,2))/(640*480)

In [71]:
X_pvm_med = np.median(X_npy, axis=(1,2))
X_pvm_mean = np.mean(X_npy, axis=(1,2))

In [72]:
X_hhr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [73]:
T2 = 0.25
X_bhhr = X_hhr.copy()
X_bhhr[X_bhhr <= T2] = 1
X_bhhr[X_bhhr < 1] = 0
X_bhhr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [74]:
X_input = np.hstack((X_pvm_med, X_pvm_mean)) * X_bhhr[:, None]

In [75]:
y_npy[y_npy > 0.75] = 1
y_npy[y_npy < 1] = 0
y_npy

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
      dtype=float32)

## SVM training

In [76]:
y_input = y_npy

In [77]:
train_split=0.75
val_split = 0.10
test_split = 1 - train_split - val_split

In [78]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,  y_test = train_test_split(X_input, y_input, test_size=test_split)
# X_train, X_val, y_train, y_val = train_test_split(X_use, y_use, test_size=val_split/(val_split+train_split))

In [79]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((185, 2), (33, 2), (185,), (33,))

In [80]:
from sklearn.svm import SVR, SVC

In [81]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [82]:
reg = LogisticRegression()
reg.fit(X_train, y_train)

LogisticRegression()

In [83]:
y_val_pred = reg.predict(X_test)
y_test, y_val_pred
print(classification_report(y_val_pred, y_test))

              precision    recall  f1-score   support

         0.0       1.00      0.70      0.82        33
         1.0       0.00      0.00      0.00         0

    accuracy                           0.70        33
   macro avg       0.50      0.35      0.41        33
weighted avg       1.00      0.70      0.82        33



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [84]:
reg2 = SVC()
reg2.fit(X_train, y_train)

SVC()

In [85]:
y_val_pred = reg2.predict(X_test)
y_test, y_val_pred
print(classification_report(y_val_pred, y_test))

              precision    recall  f1-score   support

         0.0       1.00      0.70      0.82        33
         1.0       0.00      0.00      0.00         0

    accuracy                           0.70        33
   macro avg       0.50      0.35      0.41        33
weighted avg       1.00      0.70      0.82        33



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
